language:
- cpp

before_install:
    - sudo add-apt-repository -y ppa:saiarcot895/chromium-beta
    - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
    - sudo apt-get update
    - sudo apt-get upgrade -qq

install:
    - sudo apt-get install -qq libgtest-dev libboost-regex-dev python3 cppcheck valgrind ninja-build google-mock
    - wget https://github.com/mesonbuild/meson/archive/master.zip && unzip master.zip

script:
    - mkdir build
    - python3 ./meson-master/meson.py build && ninja -C build test-valgrind cppcheckAll

notifications:
    email:
        on_failure: never
        on_success: never
