language:
   - cpp

install:
   - sudo apt-get install libgtest-dev
   - sudo apt-get install unzip
   - sudo apt-get install libboost-regex-dev

script:
    - mkdir build
    - cd build
    - cmake .. && make && ctest
