language:
   - cpp

sudo: required
dist: trusty

install:
    - sudo apt-get install -qq libgtest-dev libboost-regex-dev python3-pip cppcheck valgrind ninja-build
    - sudo pip3 install meson

script:
    - mkdir build
    - meson build
    - ninja -C build

notifications:
    email:
        on_failure: never
        on_success: never
