language:
   - cpp

sudo: required
dist: trusty

install:
    - sudo apt-get install -qq libgtest-dev libboost-regex-dev cmake cppcheck valgrind

script:
    - mkdir build
    - cd build
    - cmake .. && make && ctest

notifications:
    email:
        on_failure: change
