language:
   - cpp

sudo: required
dist: trusty

install:
    - sudo apt-get install -qq libgtest-dev libboost-regex-dev cmake cppcheck valgrind

script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug && make && ctest --output-on-failure

#notifications:
#    email:
#        on_failure: change
