language:
   - cpp

install:
    - sudo apt-get update
    - sudo apt-get install libgtest-dev unzip libboost-regex-dev cmake
    - sudo apt-get upgrade

script:
    - mkdir build
    - cd build
    - cmake .. && make && ctest
