language:
   - cpp

install:
    - sudo apt update
    - sudo apt install libgtest-dev unzip libboost-regex-dev cmake
    - sudo apt upgrade

script:
    - mkdir build
    - cd build
    - cmake .. && make && ctest
