language:
   - cpp

# we cannot build on linux because travis is severly out of date and cannot
# even provide cmake 3.0.0... so let's move to an up-to-date system
brew:
    packages:
        - boost
        - cmake

script:
    - mkdir build
    - cd build
    - cmake .. && make && ctest

notifications:
    email:
        on_failure: change
