language:
   - cpp

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - libgtest-dev
            - libboost-regex-dev
            - cmake

script:
    - mkdir build
    - cd build
    - cmake .. && make && ctest

notifications:
    email:
        on_failure: change
